{
	"schema_version": "1.6.0",
	"id": "RHSA-2016:0156",
	"modified": "2024-09-13T09:47:49Z",
	"published": "2024-09-13T09:47:49Z",
	"related": [
		"CVE-2015-8213"
	],
	"summary": "Red Hat Security Advisory: python-django security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:openstack:7::el7",
				"name": "python-django",
				"purl": "pkg:rpm/redhat/python-django"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.8.7-1.el7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2016:0156.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:openstack:7::el7",
				"name": "python-django-bash-completion",
				"purl": "pkg:rpm/redhat/python-django-bash-completion"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.8.7-1.el7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2016:0156.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:openstack:7::el7",
				"name": "python-django-doc",
				"purl": "pkg:rpm/redhat/python-django-doc"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.8.7-1.el7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2016:0156.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2016:0156"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1283553"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2016/rhsa-2016_0156.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2015-8213"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2015-8213"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2015-8213"
		},
		{
			"type": "ARTICLE",
			"url": "https://www.djangoproject.com/weblog/2015/nov/24/security-releases-issued/"
		}
	]
}
