{
	"schema_version": "1.6.0",
	"id": "RHSA-2024:9193",
	"modified": "2024-11-13T21:19:08Z",
	"published": "2024-11-13T21:19:08Z",
	"related": [
		"CVE-2024-36039"
	],
	"summary": "Red Hat Security Advisory: python3.12-PyMySQL security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:9::appstream",
				"name": "python3.12-PyMySQL+rsa",
				"purl": "pkg:rpm/redhat/python3.12-PyMySQL%2Brsa"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.1.0-3.el9"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:9193.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:9::appstream",
				"name": "python3.12-PyMySQL",
				"purl": "pkg:rpm/redhat/python3.12-PyMySQL"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.1.0-3.el9"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:9193.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:9193"
		},
		{
			"type": "ARTICLE",
			"url": "https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/9.5_release_notes/index"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2282821"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_9193.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2024-36039"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2024-36039"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-36039"
		}
	]
}
