{
	"schema_version": "1.6.0",
	"id": "RHSA-2024:0464",
	"modified": "2024-12-18T10:05:00Z",
	"published": "2024-09-18T05:16:18Z",
	"related": [
		"CVE-2023-43804",
		"CVE-2023-45803"
	],
	"summary": "Red Hat Security Advisory: python-urllib3 security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:9::baseos",
				"name": "python-urllib3",
				"purl": "pkg:rpm/redhat/python-urllib3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.26.5-3.el9_3.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:0464.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:9::baseos",
				"name": "python3-urllib3",
				"purl": "pkg:rpm/redhat/python3-urllib3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.26.5-3.el9_3.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:0464.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:0464"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2242493"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2246840"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_0464.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2023-43804"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2023-43804"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2023-45803"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2023-45803"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803"
		},
		{
			"type": "ARTICLE",
			"url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
		},
		{
			"type": "ARTICLE",
			"url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
		},
		{
			"type": "ARTICLE",
			"url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
		}
	]
}
