{
	"schema_version": "1.6.0",
	"id": "RHSA-2021:5071",
	"modified": "2024-09-18T04:21:01Z",
	"published": "2024-09-18T04:21:01Z",
	"related": [
		"CVE-2021-21419"
	],
	"summary": "Red Hat Security Advisory: Red Hat OpenStack Platform 16.1 (python-eventlet) security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:openstack:16.1::el8",
				"name": "python-eventlet",
				"purl": "pkg:rpm/redhat/python-eventlet"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:0.25.2-5.el8ost.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2021:5071.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:openstack:16.1::el8",
				"name": "python3-eventlet",
				"purl": "pkg:rpm/redhat/python3-eventlet"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:0.25.2-5.el8ost.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2021:5071.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2021:5071"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1958407"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2021/rhsa-2021_5071.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2021-21419"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2021-21419"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-21419"
		}
	]
}
