{
	"schema_version": "1.6.0",
	"id": "RHBA-2020:1232",
	"modified": "2024-09-13T16:11:00Z",
	"published": "2024-09-13T16:11:00Z",
	"related": [
		"CVE-2019-16884"
	],
	"summary": "Red Hat Bug Fix Advisory: runc bug fix update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:C/C:N/I:H/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:rhel_extras_other:7",
				"name": "runc",
				"purl": "pkg:rpm/redhat/runc"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.0.0-67.rc10.el7_8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHBA-2020:1232.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_extras_other:7",
				"name": "runc-debuginfo",
				"purl": "pkg:rpm/redhat/runc-debuginfo"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.0.0-67.rc10.el7_8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHBA-2020:1232.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHBA-2020:1232"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1791287"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2020/rhba-2020_1232.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2019-16884"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1757214"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2019-16884"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16884"
		}
	]
}
