{
	"schema_version": "1.6.0",
	"id": "RHBA-2021:1147",
	"modified": "2024-09-14T00:40:02Z",
	"published": "2024-09-14T00:40:02Z",
	"related": [
		"CVE-2021-28363"
	],
	"summary": "Red Hat Bug Fix Advisory: OpenShift Container Platform 3.11.420 bug fix and enhancement update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:openshift:3.11::el7",
				"name": "python-urllib3",
				"purl": "pkg:rpm/redhat/python-urllib3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.24.3-2.el7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHBA-2021:1147.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:openshift:3.11::el7",
				"name": "python2-urllib3",
				"purl": "pkg:rpm/redhat/python2-urllib3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.24.3-2.el7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHBA-2021:1147.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHBA-2021:1147"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1918568"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1937991"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1939961"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2021/rhba-2021_1147.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2021-28363"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1945136"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2021-28363"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2021-28363"
		}
	]
}
