{
	"schema_version": "1.6.0",
	"id": "RHSA-2019:0430",
	"modified": "2024-09-13T14:08:06Z",
	"published": "2024-09-13T14:08:06Z",
	"related": [
		"CVE-2019-3828"
	],
	"summary": "Red Hat Security Advisory: ansible security and bug fix update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:L/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:ansible_engine:2::el7",
				"name": "ansible",
				"purl": "pkg:rpm/redhat/ansible"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.7.8-1.el7ae"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2019:0430.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:0430"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1676689"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2019/rhsa-2019_0430.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2019-3828"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2019-3828"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-3828"
		},
		{
			"type": "ARTICLE",
			"url": "https://github.com/ansible/ansible/pull/52133"
		}
	]
}
