{
	"schema_version": "1.6.0",
	"id": "RHSA-2019:3704",
	"modified": "2024-11-22T12:56:46Z",
	"published": "2024-09-16T02:21:45Z",
	"related": [
		"CVE-2019-6446"
	],
	"summary": "Red Hat Security Advisory: numpy security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::appstream",
				"name": "numpy",
				"purl": "pkg:rpm/redhat/numpy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.14.3-9.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2019:3704.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::appstream",
				"name": "numpy-debugsource",
				"purl": "pkg:rpm/redhat/numpy-debugsource"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.14.3-9.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2019:3704.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::appstream",
				"name": "python3-numpy",
				"purl": "pkg:rpm/redhat/python3-numpy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.14.3-9.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2019:3704.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::appstream",
				"name": "python3-numpy-debuginfo",
				"purl": "pkg:rpm/redhat/python3-numpy-debuginfo"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.14.3-9.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2019:3704.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::appstream",
				"name": "python3-numpy-f2py",
				"purl": "pkg:rpm/redhat/python3-numpy-f2py"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.14.3-9.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2019:3704.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:3704"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.1_release_notes/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1667950"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1687873"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2019/rhsa-2019_3704.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2019-6446"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2019-6446"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
		}
	]
}
