{
	"schema_version": "1.6.0",
	"id": "RHSA-2018:2523",
	"modified": "2024-10-21T22:13:27Z",
	"published": "2024-09-13T16:52:38Z",
	"related": [
		"CVE-2018-14432"
	],
	"summary": "Red Hat Security Advisory: openstack-keystone security and bug fix update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:openstack:12::el7",
				"name": "openstack-keystone",
				"purl": "pkg:rpm/redhat/openstack-keystone"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:12.0.0-6.el7ost"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2018:2523.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:openstack:12::el7",
				"name": "python-keystone",
				"purl": "pkg:rpm/redhat/python-keystone"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:12.0.0-6.el7ost"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2018:2523.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:openstack:12::el7",
				"name": "python-keystone-tests",
				"purl": "pkg:rpm/redhat/python-keystone-tests"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:12.0.0-6.el7ost"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2018:2523.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2018:2523"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#important"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1577965"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1592446"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1606868"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2018/rhsa-2018_2523.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2018-14432"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2018-14432"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2018-14432"
		}
	]
}
