{
	"schema_version": "1.6.0",
	"id": "RHSA-2023:3550",
	"modified": "2024-09-13T18:47:32Z",
	"published": "2024-09-13T18:47:32Z",
	"related": [
		"CVE-2023-24329"
	],
	"summary": "Red Hat Security Advisory: python security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:rhel_els:6",
				"name": "python",
				"purl": "pkg:rpm/redhat/python"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.6.6-69.el6_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:3550.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_els:6",
				"name": "python-debuginfo",
				"purl": "pkg:rpm/redhat/python-debuginfo"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.6.6-69.el6_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:3550.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_els:6",
				"name": "python-devel",
				"purl": "pkg:rpm/redhat/python-devel"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.6.6-69.el6_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:3550.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_els:6",
				"name": "python-libs",
				"purl": "pkg:rpm/redhat/python-libs"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.6.6-69.el6_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:3550.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_els:6",
				"name": "python-test",
				"purl": "pkg:rpm/redhat/python-test"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.6.6-69.el6_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:3550.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_els:6",
				"name": "python-tools",
				"purl": "pkg:rpm/redhat/python-tools"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.6.6-69.el6_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:3550.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_els:6",
				"name": "tkinter",
				"purl": "pkg:rpm/redhat/tkinter"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.6.6-69.el6_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2023:3550.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2023:3550"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#important"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2173917"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2023/rhsa-2023_3550.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2023-24329"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2023-24329"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2023-24329"
		},
		{
			"type": "ARTICLE",
			"url": "https://pointernull.com/security/python-url-parse-problem.html"
		}
	]
}
