{
	"schema_version": "1.6.0",
	"id": "RHSA-2022:5602",
	"modified": "2024-11-22T19:37:04Z",
	"published": "2024-09-18T05:55:40Z",
	"related": [
		"CVE-2022-28346",
		"CVE-2022-28347"
	],
	"summary": "Red Hat Security Advisory: RHUI 4.1.1 release - Security Fixes and Enhancement Update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:L"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:rhui:4::el8",
				"name": "python-django",
				"purl": "pkg:rpm/redhat/python-django"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.2.13-2.el8ui"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2022:5602.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhui:4::el8",
				"name": "python-pulpcore",
				"purl": "pkg:rpm/redhat/python-pulpcore"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.17.6-3.el8ui"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2022:5602.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhui:4::el8",
				"name": "python38-pulpcore",
				"purl": "pkg:rpm/redhat/python38-pulpcore"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:3.17.6-3.el8ui"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2022:5602.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2022:5602"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#important"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1636435"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1890389"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2010343"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2072447"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2072459"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2079376"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2022/rhsa-2022_5602.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2022-28346"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2022-28346"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-28346"
		},
		{
			"type": "ARTICLE",
			"url": "https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2022-28347"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2022-28347"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2022-28347"
		}
	]
}
